spring.application.name=toko-online
server.port=8080

# Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tokoonline_db
spring.datasource.username=postgres
spring.datasource.password=RPL123#
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=mySecretKey12345678901234567890123456789012
app.jwt.expiration=86400000
